# MongoDB host and port. If ReplicaSet is enabled, configure all or subset of members of the cluster.
servers:
  - host: "localhost"
    port: 27017

# Specify this key if Password Encryption Support is required. If not keep it empty
# If specified, adminDBPassword and databases passwords are now the encrypted passwords.
passwordEncryptionKey: ""

# Admin DB username and password. Required if mongod is started with --auth (Authentication) else keep empty
# The user should have clusterMonitor role as a minimum
adminDBUsername: "admin"
adminDBPassword: "admin"

# Change ssl to true if mongod is started with ssl. Then specify the pemFilePath, if not keep empty.
ssl: false
pemFilePath: ""

# https://docs.mongodb.com/manual/reference/command/serverStatus/
serverStatusExcludeMetricFields: [locks, wiredTiger, tcmalloc, opcountersRepl, metrics]

#prefix used to show up metrics in AppDynamics
metricPathPrefix:  "Custom Metrics|Mongo Server|"
#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|Mongo Server|"
