#prefix used to show up metrics in AppDynamics
metricPrefix:  "Custom Metrics|Mongo Server|"
#This will create it in specific Tier. Replace <TIER_ID>
#metricPrefix:  "Server|Component:<TIER_ID>|Custom Metrics|Mongo DB|"

# MongoDB host and port. If ReplicaSet is enabled, configure all or subset of members of the cluster.
servers:
  - name: "Server 1"
    host: "localhost"
    port: 27017

  - name: "Replica"
    host: "localhost"
    port: 27018

# Admin DB username and password. Required if mongod is started with --auth (Authentication) else keep empty
# The user should have clusterMonitor role as a minimum
username: ""
password: ""

# You can either use the normal password or encrypt your password and provide the encrypted Password and encryptionKey.
# Specify this key if Password Encryption Support is required. If not keep it empty
# Do not provide both, only provide one and comment out the other.

encryptedPassword: ""
encryptionKey: ""


# Change ssl to true if mongod is started with ssl.
useSsl: false

# For each server you monitor, you will need a total of 1(by default) + 1(for serverMetrics) + 1(for replicaMetrics) + 1(for DB) + 1(for collection)
numberOfThreads: 5


# If you are using the connection section,
# any change to the connection section below requires a machine agent restart for the changes to reflect
connection:
  socketTimeout: 3000
  connectTimeout: 1000
  sslTrustStorePath: '' #if [sslTrustStorePath]: '' empty, it defaults to <MachineAgent_Home>/conf/cacerts.jks
  sslTrustStorePassword: '' # [sslTrustStorePassword: ""] defaults to ''
  sslTrustStoreEncryptedPassword: '' #provide encrypted Password if encryption is needed

